
 #include <gbmath/temp/devcamera.cpp>
 #include <gbmath/aabb.cpp>
 #include <gbmath/aabbtree.cpp>
 #include <gbmath/axies_angle.cpp>
 #include <gbmath/cilinder.cpp>
 #include <gbmath/circle.cpp>
 #include <gbmath/color3.cpp>
 #include <gbmath/color3f.cpp>
 #include <gbmath/color4.cpp>
 #include <gbmath/color4f.cpp>
 #include <gbmath/euler_angles.cpp>
 #include <gbmath/eyedata.cpp>
 #include <gbmath/float_context.cpp>
 #include <gbmath/float_context_type_e.cpp>
 #include <gbmath/frustum.cpp>
 #include <gbmath/geometry_context.cpp>
 #include <gbmath/mat22.cpp>
 #include <gbmath/mat33.cpp>
 #include <gbmath/mat44.cpp>
 #include <gbmath/normal2.cpp>
 #include <gbmath/normal3.cpp>
 #include <gbmath/object_color_type_e.cpp>
 #include <gbmath/oobb.cpp>
 #include <gbmath/plane.cpp>
 #include <gbmath/quaternion.cpp>
 #include <gbmath/ray2d.cpp>
 #include <gbmath/ray3d.cpp>
 #include <gbmath/scalar.cpp>
 #include <gbmath/sphere.cpp>
 #include <gbmath/vec2.cpp>
 #include <gbmath/vec3.cpp>
 #include <gbmath/vector2.cpp>
 #include <gbmath/vector4.cpp>
