//#include "stdafx.h"

#pragma once


 #include "aabb.cpp"
 #include "aabbtree.cpp"
 #include "arc_ball.cpp"
 #include "axies_angle.cpp"
 #include "base_camera.cpp"
 #include "cilinder.cpp"
 #include "circle.cpp"
 #include "color3.cpp"
 #include "color3f.cpp"
 #include "color4.cpp"
 #include "color4f.cpp"
 #include "euler_angles.cpp"
 #include "eyedata.cpp"
 #include "first_person_camera.cpp"
 #include "float_context.cpp"
 #include "float_context_type_e.cpp"
 #include "frustum.cpp"
 #include "geometry_context.cpp"
 #include "mat22.cpp"
 #include "mat33.cpp"
 #include "mat44.cpp"
 #include "model_view_camera.cpp"
 #include "normal2.cpp"
 #include "normal3.cpp"
 #include "object_color_type_e.cpp"
 #include "oobb.cpp"
 #include "plane.cpp"
 #include "quaternion.cpp"
 #include "ray2d.cpp"
 #include "ray3d.cpp"
 #include "scalar.cpp"
 #include "sphere.cpp"
 #include "target_camera.cpp"
 #include "vec2.cpp"
 #include "vec3.cpp"
 #include "vector2.cpp"
 #include "vector4.cpp"
#include "triangle.cpp"

#include "dependence_on_function.cpp"

 #include "drawer.cpp" 
